#!/usr/bin/python3
from pymongo import MongoClient, errors
from bson.json_util import dumps
import os
import json

MONGOPASS = os.getenv('MONGOPASS')
uri = "mongodb+srv://cluster0.pnxzwgz.mongodb.net/"
client = MongoClient(uri, username='nmagee', password=MONGOPASS, connectTimeoutMS=200, retryWrites=True)
# specify a database
db = client.fpt9nh
# specify a collection
collection = db.dp2

# mongoimport --uri $MONGODB --collection test  data.json --jsonArray

# database
directory = "data"

# create for loop
for files in os.listdir(directory): # look at files 
  with open(os.path.join(directory, files)) as f: 
    try:
        file_data = json.load(f) # load as json
    # error handling -- throw error if encountering issues loading file
    except Exception as e: 
      print(f"Error loading file: {e}")
#
    try:
      if isinstance(file_data, list): # if file data is a list, then...
        collection.insert_many(file_data) # insert several files into collection
    except Exception as e:
      print(f"Issue when importing into Mongo: {e}")
    
    
    # if file data has only one item (not a list), we'll want to use insert_one function instead
    else:
      try:
        collection.insert_one(file_data) # insert file into collection
      except Exception as e: # unless there's an error
        print("Encountered an error:", e)    
    # do other things with f
